import io.reactivex.Observable;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Observable.just("Hello RxJava")
                .subscribe(line -> System.out.println(line));
    }
}
