package com.payment;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.payment.entity.Payment;

import com.payment.PaymentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig paymentDaoConfig;

    private final PaymentDao paymentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        paymentDaoConfig = daoConfigMap.get(PaymentDao.class).clone();
        paymentDaoConfig.initIdentityScope(type);

        paymentDao = new PaymentDao(paymentDaoConfig, this);

        registerDao(Payment.class, paymentDao);
    }
    
    public void clear() {
        paymentDaoConfig.getIdentityScope().clear();
    }

    public PaymentDao getPaymentDao() {
        return paymentDao;
    }

}
